 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="<?php echo $this->url->get('system-dict/index')?>">SystemDict列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="<?php echo $this->url->get('system-dict/add')?>">
			
			 	 
					<div class="form-group"  >
						<label for="input-title"  class="col-sm-2 control-label">名字</label>
						<div class="col-sm-7">
							<input type="text" name="name" value="<?php echo $data->name?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group"  >
						<label for="input-title"  class="col-sm-2 control-label">配置</label>
						<div class="col-sm-7">
						<!-- 	<input type="text" name="value" value="<?php echo $data->value?>" class="form-control" > -->
						<textarea style="width:100%; height:300px" name="value"><?php echo $value?></textarea>
						</div>
					</div>
					 
					<div class="form-group"  >
						<label for="input-title"  class="col-sm-2 control-label">备注</label>
						<div class="col-sm-7">
							<input type="text" name="remark" value="<?php echo $data->remark?>" class="form-control" >
						</div>
					</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 	
 	 			name: {
                message: '名字',
                validators: {
                    notEmpty: {
                        message: '名字不能为空'
                    },
                }
            }, 
           
 	
 	       
 	
 	       
        
        }
    });
 
	});
 </script> 