 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="<?php echo $this->url->get($this->dispatcher->getControllerName().'/index')?>">SystemAdminMenuGroup列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="<?php echo $this->url->get($this->dispatcher->getControllerName().'/add')?>">
			
			 	 
					<div class="form-group"  style="display:none">
						<label for="input-title"  class="col-sm-2 control-label">Id</label>
						<div class="col-sm-7">
							<input type="text" name="Id" value="<?php echo $data->Id?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">菜单图标</label>
						<div class="col-sm-7">
							<input type="text" name="MenuIcon" value="<?php echo $data->MenuIcon?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">名称</label>
						<div class="col-sm-7">
							<input type="text" name="Name" value="<?php echo $data->Name?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">排序</label>
						<div class="col-sm-7">
							<input type="text" name="OrderBy" value="<?php echo $data->OrderBy?>" class="form-control" >
						</div>
					</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 	
 	 	
 	
 	 			MenuIcon: {
                message: '菜单图标',
                validators: {
                    notEmpty: {
                        message: '菜单图标不能为空'
                    },
                }
            }, 
           
 	
 	 			Name: {
                message: '名称',
                validators: {
                    notEmpty: {
                        message: '名称不能为空'
                    },
                }
            }, 
           
 	
 	 			OrderBy: {
                message: '排序',
                validators: {
                    notEmpty: {
                        message: '排序不能为空'
                    },
                }
            }, 
           
        
        }
    });
 
	});
 </script> 