 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="<?php echo $this->url->get($this->dispatcher->getControllerName().'/index')?>">SystemStore列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="<?php echo $this->url->get($this->dispatcher->getControllerName().'/add')?>">
			
			 	 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">商家Id</label>
						<div class="col-sm-7">
							<input type="text" name="store_id" value="<?php echo $data->store_id?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">logo</label>
						<div class="col-sm-7">
							<input type="text" name="logo" value="<?php echo $data->logo?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">商家名</label>
						<div class="col-sm-7">
							<input type="text" name="store_name" value="<?php echo $data->store_name?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">录入时间</label>
						<div class="col-sm-7">
							<input type="text" name="created" value="<?php echo $data->created?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">联系电话</label>
						<div class="col-sm-7">
							<input type="text" name="photo" value="<?php echo $data->photo?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">地址</label>
						<div class="col-sm-7">
							<input type="text" name="address" value="<?php echo $data->address?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">域名</label>
						<div class="col-sm-7">
							<input type="text" name="domain" value="<?php echo $data->domain?>" class="form-control" >
						</div>
					</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 	
 	 			store_id: {
                message: '商家Id',
                validators: {
                    notEmpty: {
                        message: '商家Id不能为空'
                    },
                }
            }, 
           
 	
 	 			logo: {
                message: 'logo',
                validators: {
                    notEmpty: {
                        message: 'logo不能为空'
                    },
                }
            }, 
           
 	
 	       
 	
 	       
 	
 	       
 	
 	       
 	
 	       
        
        }
    });
 
	});
 </script> 