 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="<?php echo $this->url->get($this->dispatcher->getControllerName().'/index')?>">SystemStoreUser列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="<?php echo $this->url->get($this->dispatcher->getControllerName().'/add')?>">
			
			 	 
					<div class="form-group" style="display:none">
						<label for="input-title"  class="col-sm-2 control-label">Id</label>
						<div class="col-sm-7">
							<input type="text" name="id" value="<?php echo $data->id?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">用户名</label>
						<div class="col-sm-7">
							<input type="text" name="user_name" value="<?php echo $data->user_name?>" class="form-control" >
						</div>
					</div>

					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">密码</label>
						<div class="col-sm-7">
							<input type="text" name="password" value="<?php echo $data->password?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">所属商户</label>
						<div class="col-sm-7">
							<input type="text" name="store_id" value="<?php echo $data->store_id?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">状态 </label>
						<div class="col-sm-7">
							<input type="text" name="status" value="<?php echo $data->status?>" class="form-control" >
						</div>
					</div>
					 
					 
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">用户组</label>
						<div class="col-sm-7">
							<select  class="form-control"  name="RoleId">
						   <?php foreach($Roles as $vo){?>
						   	<option value="<?php echo $vo['Id']?>" <?php if($vo['Id'] == $data->RoleId){?>selected<?php }?>><?php echo $vo['RoleName']?></option>
						   	<?php }?>
						   </select>
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">头像</label>
						<div class="col-sm-7">
							<input type="text" name="img" value="<?php echo $data->img?>" class="form-control" >
						</div>
					</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 	
 	 			user_name: {
                message: '用户名',
                validators: {
                    notEmpty: {
                        message: '用户名不能为空'
                    },
                }
            }, 
           
 	 		password: {
                message: '密码不能为空',
                validators: {
                    notEmpty: {
                        message: '密码不能为空'
                    },
                }
            }, 
        
        }
    });
 
	});
 </script> 