<div class="panel panel-default">
		<div class="panel-heading"> <strong><?php echo '12332e';?> 缓存管理</strong> </div>
		<div class="panel-body">
			<div class="bootstrap-table">
				<div class="fixed-table-container" style="padding-bottom: 0px;">
					<div class="fixed-table-body">
						<table id="data-table" class="table">
							<thead>
								<tr> 
									<th style="" data-field="name"><div class="th-inner ">名称</div>
										<div class="fht-cell"></div></th>
									<th style="" data-field="id"><div class="th-inner ">操作</div>
										<div class="fht-cell"></div></th>
								</tr>
							</thead>
							<tbody>
							<tr data-index="0">  
								<td height="36" valign="middle">APC modelsMetadata 缓存</td>
								<td style="">
								<a href="<?php echo $this->url->get('cache/deletemodelsmetadata')?>" class="btn btn-primary btn-xs">清除</a>
								</td>
							</tr>	

							<tr data-index="0">  
								<td height="36" valign="middle">数据缓存（Phpkit::cache 产生缓存）</td>
								<td style="">
								<a href="<?php echo $this->url->get('cache/deletecachedata')?>" class="btn btn-primary btn-xs">清除</a>
								</td>
							</tr>	

							</tbody>
						</table>
					</div>
					 <div id="page">
      
 </div> </div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>


