 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="<?php echo $this->url->get($this->dispatcher->getControllerName().'/index')?>">AddonAuth列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="<?php echo $this->url->get($this->dispatcher->getControllerName().'/add')?>">
			
			 	 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">ID</label>
						<div class="col-sm-7">
							<input type="text" name="Id" value="<?php echo $data->Id?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">权限名称</label>
						<div class="col-sm-7">
							<input type="text" name="Title" value="<?php echo $data->Title?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">权限代码</label>
						<div class="col-sm-7">
							<input type="text" name="AuthCode" value="<?php echo $data->AuthCode?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">权限组ID</label>
						<div class="col-sm-7">
							<input type="text" name="GroupId" value="<?php echo $data->GroupId?>" class="form-control" >
						</div>
					</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 	
 	 			Id: {
                message: 'ID',
                validators: {
                    notEmpty: {
                        message: 'ID不能为空'
                    },
                }
            }, 
           
 	
 	 			Title: {
                message: '权限名称',
                validators: {
                    notEmpty: {
                        message: '权限名称不能为空'
                    },
                }
            }, 
           
 	
 	 			AuthCode: {
                message: '权限代码',
                validators: {
                    notEmpty: {
                        message: '权限代码不能为空'
                    },
                }
            }, 
           
 	
 	 			GroupId: {
                message: '权限组ID',
                validators: {
                    notEmpty: {
                        message: '权限组ID不能为空'
                    },
                }
            }, 
           
        
        }
    });
 
	});
 </script> 