 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="<?php echo $this->url->get($this->dispatcher->getControllerName().'/index')?>">SystemAdminMenu列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="<?php echo $this->url->get($this->dispatcher->getControllerName().'/add')?>">
			
			 	 
					<div class="form-group" style="display:none">
						<label for="input-title"  class="col-sm-2 control-label">Id</label>
						<div class="col-sm-7">
							<input type="text"  name="Id" value="<?php echo $data->Id?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">链接</label>
						<div class="col-sm-7">
							<input type="text" name="Url" value="<?php echo $data->Url?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">名称</label>
						<div class="col-sm-7">
							<input type="text" name="Name" value="<?php echo $data->Name?>" class="form-control" >
						</div>
					</div>

					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">链接代码</label>
						<div class="col-sm-7">
							<input type="text" name="Code" value="<?php echo $data->Code?>" class="form-control" >
						</div>
					</div>

					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">选中菜单</label>
						<div class="col-sm-7">
							<input type="text" name="ActiveMenu" placeholder="默认选中当前链接" value="<?php echo $data->ActiveMenu?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">排序</label>
						<div class="col-sm-7">
							<input type="text" name="OrderBy" value="<?php echo $data->OrderBy?$data->OrderBy:999?>" class="form-control" >
						</div>
					</div>
					 
					<div class="form-group">
						<label for="input-title"  class="col-sm-2 control-label">组Id</label>
						<div class="col-sm-7">
						   <select  class="form-control"  name="Pid">
						   <?php foreach($GroupList as $vo){?>
						   	<option value="<?php echo $vo['Id']?>" <?php if($vo['Id'] == $data->Pid){?>selected<?php }?>><?php echo $vo['Name']?></option>
						   	<?php }?>
						   </select>
							 
						</div>
					</div>
				
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 	

 	
 	 			Url: {
                message: '链接',
                validators: {
                    notEmpty: {
                        message: '链接不能为空'
                    },
                }
            }, 
           
 	
 	 			Name: {
                message: '名称',
                validators: {
                    notEmpty: {
                        message: '名称不能为空'
                    },
                }
            }, 
           
 	
 	 			OrderBy: {
                message: '排序',
                validators: {
                    notEmpty: {
                        message: '排序不能为空'
                    },
                }
            }, 
           
 	
 	 			Pid: {
                message: '组Id',
                validators: {
                    notEmpty: {
                        message: '组Id不能为空'
                    },
                }
            }, 
           
        
        }
    });
 
	});
 </script> 